### ISSUE TITLE
idea: layout qualifiers

### ISSUE THREAD

**Issue by mattdesl** [stackgl/glslify#27]
Just tossing this idea out there.

As a transform, we could emulate layout qualifiers with glslify using the standard GLSL syntax: 

```layout(location = 0) in vec3 position;```

This would need a few changes to gl-shader-core and its adapter to accept initial attribute locations (as opposed to recompiling needlessly).

**Comment by vorg** [comment]
Why this is closed?

**Comment by mattdesl** [comment]
Doesn't seem to be relevant to glslify core since it just returns strings now. Instead could be developed as a transform. 

In a larger scope, I think it would be good to have a transform that inlines attribute/uniform data, and maybe other diagnostics like this layout qualifier stuff.

**Comment by mattdesl** [comment]
p.s. gl-shader now accepts attribute locations so this should be pretty doable.
