### ISSUE TITLE
Question : Possible bug? Can't add path to shader using a variable

### ISSUE THREAD

**Issue by sortofsleepy** [stackgl/glslify#35]
Now I'm sure this is just going to turn out to be one of those situations where I'm missing something blindingly obvious but I've run into a bit of a odd issue when using glslify and browserify. 

For whatever reason, if I include a path to a shader using a variable, ie

```javascript
var vertex = "./shaders/render.vert.glsl";
var fragment = "./shaders/render.frag.glsl";
var test = glslify({
    vertex:vertex,
    fragment:fragment
});

```
I always get the error message `you should bundle your code using glslify as a transform` when I try to run the resulting js in a browser. 

The command I've tried to compile with browserify is 
```javascript
browserify <whatever>.js -t glslify > bundle.js
```

At first I thought it was just my project setup but this still occurs even with a very simple test project.

It's not a dealbreaker and I can work around it, but I was just curious as to what could be the issue as it's a very strange one. 

If it matters at all, I'm trying to integrate things into a Three.js project but I still get the error even after setting `sourceOnly` to true.

Thanks!

**Comment by mattdesl** [comment]
Hey @sortofsleepy, it's most likely because the paths have to be statically analyzable within the `glslify()` method call. AST will only take you so far before your script actually needs to be evaluated to determine the paths (like `path = [ base, 'foo.vert' ].join('/')`).

Try this: 

```js
var test = glslify({
    vertex:"./shaders/render.vert.glsl",
    fragment:"./shaders/render.frag.glsl"
});
```

**Comment by sortofsleepy** [comment]
@mattdesl AH, got it got it. 

yup yup, I knew string paths work fine, sorry if that wasn't clear, the hope was to integrate glslify into a shader loader of sorts but it's not a huge deal to work around that. 

Thanks!
