### ISSUE TITLE
Webpack & other Bundlers

### ISSUE THREAD

**Issue by mattdesl** [stackgl/glslify#36]
Might be worth exploring glslify tooling for webpack/jspm/etc so that stackgl modules as a whole aren't so strictly tied to browserify.

**Comment by hughsk** [comment]
I'm not a big fan of webpack, but still agree with you on this one. Don't want to lock anybody into one particular thing just because we prefer it when there are alternatives out there :)

**Comment by mikolalysenko** [comment]
+1

**Comment by swannknani** [comment]
+1 for webpack :)

**Comment by marklundin** [comment]
+1

Would be really handle to separate this lib from it's bundler

**Comment by hughsk** [comment]
I should have something out for webpack later today, if anybody would like to maintain it then let me know! Also worth noting that glslify can be used via the [CLI](https://github.com/stackgl/glslify#cli) and [Node API](https://github.com/stackgl/glslify#module-api) :)

**Comment by hughsk** [comment]
Done! https://github.com/stackgl/glslify-loader

**Comment by mattdesl** [comment]
:+1:  nice
