### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by hughsk** [stackgl/glslify#44]
The following does not compile: https://gist.github.com/mattdesl/0ea2f97ca44d3f933ade

**Comment by jamieowen** [comment]
@mattdesl Had a quick look at this one as well and compared to problems with glsl-blend.   The problem looks identical.   With glsl-blend, here's the test case just tested in the command line:

This works :
```glsl
#pragma glslify: blendVividLight = require(glsl-blend/vivid-light)
#pragma glslify: blendColorDodge = require(glsl-blend/color-dodge)
```
But this doesn't :
```glsl
#pragma glslify: blendColorDodge = require(glsl-blend/color-dodge)
#pragma glslify: blendVividLight = require(glsl-blend/vivid-light)
```

Internally, VividLight requires ColorDodge ( and ColorBurn ).  
If ColorDodge is declared first, the function is named **blendColorDodge_1_0** but inside the VividLight function, it is referencing a function called **blendColorDodge_1_0_2_3** which obviously doesn't exist.

**Comment by vorg** [comment]
I have the same problem

```GLSL
//main.frag
#pragma glslify: correctGammaInput = require(./pbr/correctGammaInput.glsl)
#pragma glslify: getAlbedo = require(./pbr/albedoConst.frag)
```

```GLSL
//albedoConst.frag
#pragma glslify: correctGammaInput = require(./correctGammaInput.glsl)

uniform vec4 albedoColor; //assumes sRGB color, not linear

void getAlbedo(inout FragData data) {
  data.albedo = correctGammaInput(albedoColor.rgb);
}
```

results in

```javascript
Error: ERROR: 0:67: Invalid call of undeclared identifier 'correctGammaInput_2_0_1_4'
```

as the top import declares `correctGammaInput_2_0`

**Comment by hughsk** [comment]
Oh man, this is not a nice bug at all. Looking into it :)

**Comment by vorg** [comment]
Any progress? Writing some color conversion modules and got stuck again

```glsl
#pragma glslify: lab2rgb = require(../glsl-lab2rgb)
#pragma glslify: hcl2rgb = require(../glsl-hcl2rgb)
...
color = hcl2rgb(h, c, l);
```

and I get this error as `glsl-hcl2rgb` depends internally on `glsl-lab2rgb`. Flipping above requires works as for @mattdesl .

```Invalid call of undeclared identifier 'lab2rgb_1_2_2_5'```

**Comment by mattdesl** [comment]
Hugh added a failing test case:
https://github.com/stackgl/glslify/blob/master/test/nest-conflicts.js

Seems to be from [glslify-bundle](https://github.com/stackgl/glslify-bundle).

It looks like the `local` name gets turned into `foo_x_y`. he next time we see that local it becomes `foo_x_y_x_y`.  I won't be able to do any programming this weekend (my wrist is out of commission) but hopefully next week I can look into it. Hugh probably has a better idea of how to fix though.

**Comment by MikkoH** [comment]
Yep had exactly what @mattdesl was describing above happen to me.

**Comment by edankwan** [comment]
+1 on this. I just hit the wall.
