### ISSUE TITLE
confusing bug(?) regarding matrix multiplication

### ISSUE THREAD

**Issue by thejmazz** [stackgl/glslify#63]
Working through [shader school](https://github.com/stackgl/shader-school) lesson 6, this works:

```glsl
mat2 matrixPower(highp mat2 m, const int n) {
  // Raise the matrix m to nth power where 0 <= n < 16 is an integer
  // For example:
  // matrixPower(m, 2) = m * m

  // Works
  highp mat2 p = m;
  for (int i = 1; i < 16; i++) {
      if (i == n) return p;
      p *= m;
  }
  return p;
}

//Do not change this line or the name of the above function
#pragma glslify: export(matrixPower)
```

producing: <img width="1279" alt="screen shot 2015-10-18 at 11 50 56 pm" src="https://cloud.githubusercontent.com/assets/1270998/10569606/d5c97718-75f6-11e5-81e8-4fb9deed1ba9.png">

whereas this fails the exercise:

```glsl
mat2 matrixPower(highp mat2 m, const int n) {
  // Doesn't work?
  for (int i = 1; i < 16; i++) {
      if (i == n) return m;
      m *= m;
  }
  return m;
}
```

Producing: 
<img width="1278" alt="screen shot 2015-10-18 at 11 50 19 pm" src="https://cloud.githubusercontent.com/assets/1270998/10569658/98eebb18-75f7-11e5-82de-0b173a4173e9.png">

The second seems to "deform" the image faster - the first few iterations it looks alright, though out of sync with the left half of the screen, "the goal". Ultimately it "deforms" too much and ends up as this greenish square. Is this part of how GLSL works or perhaps a bug in glslify?

Oh ya and I'm running El Capitan 10.11 with Intel Iris Graphics 6100 1536 MB. Chrome 45.0.2454.101, FF 41.0.2.

Cheers.

**Comment by mikolalysenko** [comment]
In your second image, you have a bug where you are computing `m^(2^n)`, not `m^n`.  This is because you are squaring `m` at each step.

**Comment by thejmazz** [comment]
Ohhh I get it. Silly mistake. The first version multiplies `p` by `m`  and `m` never changes. The second is multiplying by `m` which is changing and being squared each step. 

So no bug :)  And thanks for the help @mikolalysenko :)
