### ISSUE TITLE
x.match is not a function

### ISSUE THREAD

**Issue by z3t0** [stackgl/glslify#67]
Hi,

I can't seem to do much as I simply get x.match is not a function when trying to run browserify.

https://gist.github.com/z3t0/983ffa04dd2e8bf41536

**Comment by hughsk** [comment]
Hi @z3t0, it appears that you're using the old glslify@1 API here. Please see the migration guide in the readme (thankfully it's quite short!): https://github.com/stackgl/glslify#migrating-from-glslify1-to-glslify2

I'll make glslify provide a more constructive error for this before closing the issue.

**Comment by z3t0** [comment]
@hughsk Thanks! It's all working now. I was trying to revive an old project with too many dependencies to figure out where things were breaking, and yes providing a more informative error would be great.

**Comment by hughsk** [comment]
Great! Added the error message, should hopefully fix things up for people in the future :D

**Comment by noisyneuron** [comment]
documentation for migrating seems to have moved - for anyone looking, its here :  http://stack.gl/packages/#stackgl/glslify
