### ISSUE TITLE
ES6 strings do not work

### ISSUE THREAD

**Issue by dfcreative** [stackgl/glslify#68]
Hi!
glslify seems to not work with ES6 strings:
```js
//an example from readme
var glslify = require('glslify')

var src = glslify(`
  precision mediump float;

  void main() {
    gl_FragColor = vec4(1.0);
  }
`, { inline: true })
```
Running `browserify -t glslify index.js` gives 
```js
//...browserify wrapper
var src = glslify(`
  precision mediump float;

  void main() {
    gl_FragColor = vec4(1.0);
  }
`, { inline: true })
//...end of wrapper
```
So glslify wasn’t applied. Transforming ES6 strings to ES5 strings makes glslify work.

**Comment by dfcreative** [comment]
@substack @mattdesl I guess that’s the problem of node-falafel, which by default uses acorn@1.0.0, which just ignores option `{ ecmaVersion: 6 }` passed to it from `static-module`.
The [PR](https://github.com/substack/node-falafel/pull/52) should fix it.

**Comment by mikolalysenko** [comment]
This sucks, I'm gonna take a shot at fixing it.

**Comment by yoshuawuyts** [comment]
this is how we look for template strings in `sheetify` - https://github.com/stackcss/sheetify/blob/master/transform.js#L84-L86

**Comment by dfcreative** [comment]
Yep. Due to old acorn in falafel we cannot even do like this:
```js
regl({
	frag: `
	precision highp float;

	${glslify('glsl-noise/simplex/2d')}
...
```
glslify experience becomes really frustrating.

Does anyone able to publish [updated falafel](https://github.com/substack/node-falafel/pull/52#issuecomment-214001690)? @substack seem to ignore messages from the repo.

That should fix this bug.

**Comment by mikolalysenko** [comment]
A temporary work around is to use [babel-plugin-glslify](https://github.com/stackgl/babel-plugin-glslify), though it requires you to set up babelify.

**Comment by substack** [comment]
template strings are supported without workarounds in version 6
