### ISSUE TITLE
es6 template strings for inline mode

### ISSUE THREAD

**Issue by yoshuawuyts** [stackgl/glslify#70]
:rotating_light: syntax shedding of bikes :rotating_light:

I reckon it'd be cool if inline mode
```js
var src = glslify(`
  precision mediump float;

  void main() {
    gl_FragColor = vec4(1.0);
  }
`, { inline: true })
```
was this instead
```js
const frag = gl`
  precision mediump float;

  void main() {
    gl_FragColor = vec4(1.0);
  }
`
```
I've managed to do it for [sheetify](https://github.com/yoshuawuyts/sheetify/tree/tagged-template) using [falafel](https://github.com/substack/falafel) - perhaps this would work nicely for `glslify` - also removes the requirement for `babel` to have inline template strings

**Comment by substack** [comment]
This is supported in version 6.
