### ISSUE TITLE
Usage with other browserify transforms

### ISSUE THREAD

**Issue by jnordberg** [stackgl/glslify#73]
Why is the browserify transform inline replacing in the javascript? Why not just let `require('./my-shader.glsl')` transform to something like `module.exports = "<shader source>";` like that there's no compatibility issues.

**Comment by yoshuawuyts** [comment]
`require('./my-shader.glsl')` would break the [node modules spec](https://nodejs.org/api/modules.html). Instead we've opted to go for a similar approach as [brfs](https://github.com/substack/brfs). There shouldn't be any compat issues with other transforms, if you're running into bugs we definitely would like to hear about them. I hope my explanation makes sense. Cheers! :sparkles:

**Comment by jnordberg** [comment]
Thanks for the response, and you're right, there wasn't any compat issue. I just had to get my transforms loaded in the correct order :blush:

Curious though why you think that would break the module spec?

**Comment by yoshuawuyts** [comment]
`require()` can only parse JavaScript and derivatives natively (e.g. JSON); when porting in stuff like CSS or GLSL which isn't intended to become part of the dependency tree, you're basically overloading the `require()` semantics - which is a very bad idea

**Comment by jnordberg** [comment]
I don't see how having to `require('glslify')` and doing some special calls that are inline replaced is less unexpected behaviour than that `require('./shader.glsl')` returns my shader. That's how the majority of browserify transforms work (and where designed to work AFAIK).

And the fact that JSON is supported by require contradicts your statement that it's not intended for use as a resource loader. If we where to adhere to the node.js module spec by the letter browserify wouldn't be possible.

I wouldn't care if this was just a "style" choice, but this method of injecting the shaders degrades browserify's bundle performance a lot since every file in my project is parsed to look for glslify calls (not to mention the complexity it must add to your bundling code).

**Comment by vorg** [comment]
@jnordberg For me it's crucial that these special calls `glslify(__dirname + '/shader.glsl')` still work in node. Together with [glslify-promise](https://github.com/stackgl/glslify-promise) I can load shader with or without the browser. `require('shader.glsl')` would break that.

> I wouldn't care if this was just a "style" choice, but this method of injecting the shaders degrades browserify's bundle performance a lot since every file in my project is parsed to look for glslify calls (not to mention the complexity it must add to your bundling code).

That indeed is a problem. Especially if you would like to make libraries that browserify shaders for internal use. I have and FX library with 10 effects and compiling them on the go is getting out of hand. I'm currently considering browserifying them once on library build and use `brfs` in production.

**Comment by mattdesl** [comment]
Require overloads also overlook the larger problem of passing options like `transform`. The webpack way (using query strings) is pretty darn ugly. 😁 

@vorg
There is some value in transpiling your code to inline the shaders, so a module doesn't need to depend on glslify to work. Ideally something like Babel would be used, but it does not support asynchronous transforms. 

Transpiling is kinda clunky though. See here for discussion: https://gist.github.com/mattdesl/aaf759da84cc44c22305

**Comment by jnordberg** [comment]
@vorg Yeah, that wouldn't work.. 

But more of a node problem really, I wish the node team had looked at improving require.extensions instead of just yelling ANTIPATTERN and deprecating it, making platform interoperability much harder than it has to be :/

I'll have a look at creating a separate module that transforms only `require('*.glsl')` calls, won't work with node but at least it's an alternative for people like me who only needs to run in the browser (how are you running shaders in node btw?:)

@mattdesl What's wrong with the [browserify way](https://github.com/substack/node-browserify#btransformtr-opts) of passing options?

**Comment by vorg** [comment]
@jnordberg I use [my engine](https://github.com/pex-gl/) with browsers but also (mostly) [Plask](http://plask.org) and [Electron](http://electron.atom.io) both of which are node based environments that work without browserifying stuff.

**Comment by mattdesl** [comment]
@jnordberg The package.json options apply a glslify transform to every inlined call. With the glslify syntax you can specify options per-shader, which can be handy.

```js
const frag = glslify(`
  void main () { ... }
`, { inline: true, transform: [ 'foobar' ] })
```

One benefit to the `require()` overload approach is that shaders will be de-duplicated because of the require cache. :smile:

**Comment by jnordberg** [comment]
Here we go https://github.com/jnordberg/glslify-bare

Kudos to the stackgl team for breaking out the components so cleanly, was super easy to implement an alternative transform.

@mattdesl ah, I see, made a note of it in the README for my module :)

@vorg that looks super cool! Had no idea that even was a thing
