### ISSUE TITLE
May build the package without browserify?

### ISSUE THREAD

**Issue by polokobe** [stackgl/glslify#76]
Hi:
    when I use the  glslify in the frontend, I found we must use browserify to transform; I also found browser.js in the dic. Maybe it will be ok that we put builded file in the browser.js , then the users cannot need to use browserify to transform.

**Comment by substack** [comment]
You can now use the API directly from node or electron in 6.0.0 so it should be easier to integrate into non-browserify workflows too.

**Comment by polokobe** [comment]
@substack  Thanks, I'll have a try. Hope it would work fine in the pure frontend environment!
